In [ ]:
# 高级处理-缺失值处理

# 如何处理nan
- 获取缺失值的标记方式(NaN或者其他标记方式)

- 如果缺失值的标记方式是NaN

    - 判断数据中是否包含NaN：
        - pd.isnull(df),
        - pd.notnull(df)
 
    - 存在缺失值nan:

        - 1、删除存在缺失值的:dropna(axis='rows')
            - 注：不会修改原数据，需要接受返回值

        - 2、替换缺失值:fillna(value, inplace=True)
            - value:替换成的值
            - inplace:True:会修改原数据，False:不替换修改原数据，生成新的对象

- 如果缺失值没有使用NaN标记，比如使用"？"
    - 先替换‘?’为np.nan，然后继续处理

# 电影数据的缺失值处理

- 电影数据文件获取

In [3]:
import pandas as pd
# 读取电影数据
movie = pd.read_csv("./IMDB-Movie-Data.csv")
movie.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

## 判断缺失值是否存在
- pd.notnull()

In [5]:
pd.notnull(movie)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,False,True
8,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,True,True,True,True,True,True
13,True,True,True,True,True,True,True,True,True,True,True,True
14,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,True,True,True,True,True,True,True,True,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True
20,True,True,True,True,True,True,True,True,True,True,True,True
21,True,True,True,True,True,True,True,True,True,True,True,True
22,True,True,True,True,True,True,True,True,True,True,False,True
23,True,True,True,True,True,True,True,True,True,True,True,True
24,True,True,True,True,True,True,True,True,True,True,True,True
25,True,True,True,True,True,True,True,True,True,True,False,False
26,True,True,True,True,True,True,True,True,True,True,True,False
27,True,True,True,True,True,True,True,True,True,True,True,False
28,True,True,True,True,True,True,True,True,True,True,True,True
29,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
970,True,True,True,True,True,True,True,True,True,True,True,True
971,True,True,True,True,True,True,True,True,True,True,True,False
972,True,True,True,True,True,True,True,True,True,True,True,True
973,True,True,True,True,True,True,True,True,True,True,True,True
974,True,True,True,True,True,True,True,True,True,True,True,True
975,True,True,True,True,True,True,True,True,True,True,True,True
976,True,True,True,True,True,True,True,True,True,True,False,True
977,True,True,True,True,True,True,True,True,True,True,False,True
978,True,True,True,True,True,True,True,True,True,True,False,True
979,True,True,True,True,True,True,True,True,True,True,True,True
980,True,True,True,True,True,True,True,True,True,True,True,True
981,True,True,True,True,True,True,True,True,True,True,True,True
982,True,True,True,True,True,True,True,True,True,True,True,True
983,True,True,True,True,True,True,True,True,True,True,True,True
984,True,True,True,True,True,True,True,True,True,True,True,True
985,True,True,True,True,True,True,True,True,True,True,True,True
986,True,True,True,True,True,True,True,True,True,True,True,True
987,True,True,True,True,True,True,True,True,True,True,True,True
988,True,True,True,True,True,True,True,True,True,True,False,True
989,True,True,True,True,True,True,True,True,True,True,True,False
990,True,True,True,True,True,True,True,True,True,True,True,True
991,True,True,True,True,True,True,True,True,True,True,True,True
992,True,True,True,True,True,True,True,True,True,True,True,False
993,True,True,True,True,True,True,True,True,True,True,True,True
994,True,True,True,True,True,True,True,True,True,True,True,True
995,True,True,True,True,True,True,True,True,True,True,False,True
996,True,True,True,True,True,True,True,True,True,True,True,True
997,True,True,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,True,False,True
999,True,True,True,True,True,True,True,True,True,True,True,True

In [8]:
import numpy as np
np.all(pd.notnull(movie))

False

## 存在缺失值nan,并且是np.nan

- 1、删除

pandas删除缺失值，使用dropna的前提是，缺失值的类型必须是np.nan

In [10]:
# 不修改原数据
movie.dropna()

# 可以定义新的变量接受或者用原来的变量名
data = movie.dropna()

- 2、替换缺失值

In [11]:
# 替换存在缺失值的样本的两列
# 替换填充平均值，中位数
# moive['Revenue (Millions)'].fillna(movie['Revenue (Millions)'].mean(),inplace=True)

In [ ]:
for i in movie.columns:
    if np.all(pd.notnull(movie[i]))==False: